import HeroBanner from "@/components/HeroBanner";
import HeroBanner2 from "@/components/HeroBanner2";
import HeroGrids from "@/components/HeroGrids";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>MosaicVa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      <main className="block overflow-hidden">
        <Navbar/>
        <HeroBanner/>
        <HeroBanner2 />
        <HeroGrids />
      </main>
    </>
  );
}
